import streamlit as st

# Title of the app
st.title('TinyTest1')

# Description of the app
st.write('App generated by AI')

# Add, Subtract, Multiply, Divide buttons

upper_number = st.number_input('Enter the first number', value=0.0)
lower_number = st.number_input('Enter the second number', value=0.0)

operation = st.selectbox("Select operation", 
    ["Add", "Subtract", "Multiply", "Divide"], 
    index=0)

# Perform the calculation based on the selected operation
if operation == "Add":
    result = upper_number + lower_number
    st.write(f'Result: {result}')
elif operation == "Subtract":
    result = upper_number - lower_number
    st.write(f'Result: {result}')
elif operation == "Multiply":
    result = upper_number * lower_number
    st.write(f'Result: {result}')
else:
    if lower_number != 0:
        result = upper_number / lower_number
        st.write(f'Result: {result}')
    else:
        st.error('Cannot divide by zero!')