# ollama/orchestrator.py
import os
import logging
import requests
import json
import re

logger = logging.getLogger("OllamaOrchestrator")

class OllamaOrchestrator:
    def __init__(self):
        self.ollama_url = "http://localhost:11434/api/generate"
        self.model = "gemma3"  # ✅ استخدم gemma3
        self.temperature = 0.1  # خفض لنتائج أكثر دقة
        self.num_predict = 2048  # حد عدد الرموز
        self.num_ctx = 2048  # حجم السياق
    
    def generate_ai(self, project_name, description):
        logger.info(f"🦙 Ollama generating: {project_name}")
        
        # تحقق من تشغيل Ollama
        if not self._is_ollama_running():
            return {"status": "failed", "reason": "Ollama not running"}
        
        project_path = os.path.join("projects", project_name)
        os.makedirs(project_path, exist_ok=True)
        
        # ✅ Prompt محسن للحصول على JSON صحيح
        prompt = f"""You are an expert Python developer. Generate a complete Streamlit application.

USER REQUEST: {description}
PROJECT NAME: {project_name}

IMPORTANT RULES:
1. Return ONLY valid JSON. No explanations before or after.
2. All strings must be properly closed with quotes.
3. Use double quotes (") for all strings.
4. Escape internal double quotes with backslash (\\").
5. Use newline escape (\\n) for line breaks.

Return EXACTLY this structure:
{{
    "main.py": "import streamlit as st\\n\\nst.title('{project_name}')\\n\\nst.write('App generated by AI')",
    "helpers.py": "# Helper functions will be here",
    "config.py": "APP_NAME = '{project_name}'\\nVERSION = '1.0'",
    "database.py": "# No database needed",
    "start_app.bat": "@echo off\\nstreamlit run main.py\\npause"
}}

Generate appropriate code based on the user's request. Make sure all string literals are properly closed."""
        
        payload = {
            "model": self.model,
            "prompt": prompt,
            "stream": False,
            "options": {
                "temperature": self.temperature,
                "num_predict": self.num_predict,
                "num_ctx": self.num_ctx
            }
        }
        
        try:
            print("🦙 Calling Ollama (gemma3)... هذا قد يستغرق 30-90 ثانية")
            response = requests.post(self.ollama_url, json=payload, timeout=180)
            result = response.json()
            raw_text = result.get('response', '')
            
            # استخراج JSON
            match = re.search(r'\{.*\}', raw_text, re.DOTALL)
            if match:
                json_str = match.group()
                try:
                    files = json.loads(json_str)
                    
                    # التحقق من صحة الملفات
                    required = ["main.py", "helpers.py", "config.py", "database.py", "start_app.bat"]
                    for key in required:
                        if key not in files:
                            files[key] = f"# {key}\nprint('{key}')"
                    
                    # حفظ الملفات
                    for filename, content in files.items():
                        with open(os.path.join(project_path, filename), "w", encoding="utf-8") as f:
                            f.write(content)
                        print(f"✅ Created: {filename}")
                    
                    return {"status": "completed", "path": project_path, "files": list(files.keys())}
                    
                except json.JSONDecodeError as e:
                    print(f"❌ JSON decode error: {e}")
                    return {"status": "failed", "reason": f"Invalid JSON: {e}"}
            else:
                print("❌ No JSON found")
                return {"status": "failed", "reason": "No JSON found"}
                
        except Exception as e:
            print(f"❌ Error: {e}")
            return {"status": "failed", "reason": str(e)}
    
    def _is_ollama_running(self):
        try:
            r = requests.get("http://localhost:11434/api/version", timeout=2)
            return r.status_code == 200
        except:
            return False